# This is a basic workflow to help you get started with Actions

name: Publish
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    strategy:
      matrix:
        kind: ['windows']
        include:
          - kind: windows
            os: windows-latest
            target: win-x64
            framework: netcoreapp3.1
          - kind: windows
            os: windows-latest
            target: win-x64
            framework: net48
          - kind: windows
            os: windows-latest
            target: win-x64
            framework: net472
          - kind: windows
            os: windows-latest
            target: win-x64
            framework: net471
    runs-on: ${{ matrix.os }}
    env:
      Project_path:  Analogy.LogViewer.SerialPort/Analogy.LogViewer.SerialPort.csproj     
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

        # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    # Buid the application 
    - name: Build the application
      run: | 
        dotnet publish $env:Project_path --framework "${{ matrix.framework }}" --runtime "${{ matrix.target }}" -c Release -o tmp
        7z a -tzip "${{ matrix.framework }}.zip" "./tmp/*"
        # Delete output directory
        rm -r tmp
        
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: "${{ matrix.framework }}.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
